Add lookup for translating General_Category longnames
Raku/nqp pull request #820
Opened 2024-04-24 07:52 UTC by ab5tract

Also fix broken shortnames "L", "M", "N", "P", "S", "Z", and "C".

This fixes R#5486 and R#5372.

2024-04-24 08:06 UTC, niner requested changes
Please describe the bug this commit fixes in the commit message.

2024-04-24 10:32 UTC, ab5tract commented on src/QRegex/Cursor.nqp
> +        my $constraint-property := nqp::istype($obj, nqp::gethllsym('Raku', 'Block'))
True, there is a cross-dependency on a Raku MR that I haven't pushed yet.

2024-04-24 20:24 UTC, ab5tract commented on src/QRegex/Cursor.nqp
> +        my $constraint-property := nqp::istype($obj, nqp::gethllsym('Raku', 'Block'))
This is no longer an issue as the approach has shifted all of this logic into Rakudo itself (where it rightly belongs).

Thanks for your help!

2024-04-26 12:24 UTC, lizmat approved these changes

2024-04-27 14:54 UTC, merged